Section A: Data Structures & Control Structures

1. Create a list of 5 integers.
Perform and print the result of the following operations:
append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

Original List: [10, 20, 30, 40, 50]


In [2]:
# 1. append() : Add a single element at the end
numbers.append(60)
print("After append(60):", numbers)

After append(60): [10, 20, 30, 40, 50, 60]


In [3]:
# 2. extend() : Add multiple elements at the end
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]


In [4]:
# 3. insert() : Insert at a specific position (index, value)
numbers.insert(2, 25)  # Insert 25 at index 2
print("After insert(2, 25):", numbers)

After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]


In [5]:
# 4. remove() : Remove first occurrence of a value
numbers.remove(40)  # Removes number 40
print("After remove(40):", numbers)

After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]


In [6]:
# 5. pop() : Remove element at a given index (default last)
popped = numbers.pop()  # Removes last element
print("After pop():", numbers, "| Popped value:", popped)

After pop(): [10, 20, 25, 30, 50, 60, 70] | Popped value: 80


In [7]:
# 6. index() : Get index of first occurrence
print("Index of 30:", numbers.index(30))

Index of 30: 3


In [8]:
# 7. count() : Count occurrences of an element
print("Count of 20:", numbers.count(20))

Count of 20: 1


In [9]:
# 8. sort() : Sort in ascending order
numbers.sort()
print("After sort():", numbers)

After sort(): [10, 20, 25, 30, 50, 60, 70]


In [10]:
# 9. reverse() : Reverse the list
numbers.reverse()
print("After reverse():", numbers)

After reverse(): [70, 60, 50, 30, 25, 20, 10]


In [11]:
# 10. clear() : Remove all elements
temp_list = numbers.copy()   # Copy before clearing to show effect
numbers.clear()
print("After clear():", numbers)

After clear(): []


2. Create a tuple that stores 3 student names.
Try changing the second name in the tuple. What happens? Explain why

In [12]:
# Create a tuple of 3 students name
Students = ("Rohan", "Priya", "Rohit")
print("Original tuple:", Students)

Original tuple: ('Rohan', 'Priya', 'Rohit')


In [13]:
# Try changing the second name in tuple
Students[3] = "Megha"

TypeError: 'tuple' object does not support item assignment

Tuple gives TypeError: 'tuple' object does not support item assignment.
In python tuples are immutable. We can not change tuple values, we can only access those values do the operations.


3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [16]:
# Create a set of integers
numbers = {1, 2, 3, 2, 4, 1, 5}
print("Given set is", numbers)

Given set is {1, 2, 3, 4, 5}


A set in Python is an unordered collection of unique elements. When we create a set, duplicate values are automatically removed.
That’s why even though we added 1 and 2 twice, they only appear once in the output.

4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [17]:
# Create a dictionary. keys: 'name', 'age', 'city'
Details = {'name' : "Vinay Powar", 'age' : 28, 'city' : "Pune"}
print("Original Dictionary:", Details)

Original Dictionary: {'name': 'Vinay Powar', 'age': 28, 'city': 'Pune'}


In [18]:
# Update the age and add new key 'email'
Details['age'] = 30 
Details['email'] = "vinay02@gmail.com"

In [19]:
# Print the final dictionary
print("Final Dictionary:", Details)

Final Dictionary: {'name': 'Vinay Powar', 'age': 30, 'city': 'Pune', 'email': 'vinay02@gmail.com'}


5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [20]:
#Taking input from user
age = int(input("Enter your age: "))

# Checking eligiblity to vote
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")


Enter your age:  902


You are eligible to vote.


6. Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [21]:
# Taking input from user
marks = int(input("Enter your marks: "))

# Checking conditions
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")


Enter your marks:  81


Grade: B


7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [22]:
# Taking number as input
num = int(input("Enter a number: "))

# Checks if the number is positive
if num > 0:
    print("The number is positive.")
    
    # Checks if it is also even
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("And it is odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")


Enter a number:  49


The number is positive.
It is odd.


Section B: Numpy

8. Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [31]:
import numpy as np

# Scalar array
scalar = np.array(5)
scalar

array(5)

In [32]:
# A 1D array with values 1 to 5
one_D = np.array([1, 2, 3, 4, 5])
one_D

array([1, 2, 3, 4, 5])

In [33]:
# A 2D array (2x3) with values from 10 to 60 in steps of 10
two_D = np.array([[10, 20, 30],
                  [40, 50, 60]])
two_D

array([[10, 20, 30],
       [40, 50, 60]])

9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [37]:
from numpy import random as rd

# Generate a 4x4 array of random integers
arr = rd.randint(0, 101, size=(4, 4))

# Print the array
print(arr)


[[30  7 29 55]
 [65 58 58 24]
 [49  2 95 65]
 [42 10  1 96]]


10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [39]:
import numpy as np
import pandas as pd

In [41]:
# Create a 2D numpy array of shape (3x3)
arr_2D = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
arr_2D

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [43]:
# Convert it into a pandas DataFrame with column name
df = pd.DataFrame(arr_2D, columns=['A', 'B', 'C'])

# Print DataFrame
print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90
